---
openapi: "3.1.0"

info:
  description: |
    ## develop
    hello world
      - list
        - A
        - B

  version: 1.0.0
  title: API Docs
  contact:
    name: kijimad
    email: norimaking777@gmail.com

servers:
  - url: http://localhost:8080
    description: go server
  - url: http://localhost:6969
    description: mock(Prism)

tags:
  - name: Pet
    description: |
      pet

paths:
  /pets:
    get:
      summary: list pets
      description: list pets
      operationId: list_pets
      tags:
        - Pet
      parameters:
        - $ref: "#/components/parameters/Limit"
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                required:
                  - pets
                properties:
                  pets:
                    $ref: "#/components/schemas/Pets"
              examples:
                case1:
                  summary: exist pets
                  $ref: "#/components/examples/PetsResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Pets:
      type: array
      description: list pets
      items:
        properties:
          id:
            type: integer
            description: pet ID
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  examples:
    PetsResponse:
      description: pets
      value:
        pets:
          - id: 1
            name: dog
          - id: 2
            name: cat
  parameters:
    Limit:
      name: limit
      in: query
      description: data count
      required: false
      schema:
        type: integer
        format: int32
